apiVersion: v1
kind: Service
metadata:
  name:  bigid-java-service
  namespace: bigid
spec:
  type: NodePort
  selector:
    app: bigid-java
  ports:
  - nodePort: 30082
    port: 8000
    targetPort: 8000
